// /////////////////////////////////////////////////////////////////
// Generated by axel-plugin wizard
// /////////////////////////////////////////////////////////////////

/* (C) MyCompany */


/* Put a short description of your plugin here */

/* MyCompany-contact@mycompany.com-http://www.mycompany.com */

#ifndef MYPLUGINDEFAULTDATAWRITER_H
#define MYPLUGINDEFAULTDATAWRITER_H

#include <axlCore/axlAbstractDataWriter.h>

#include "MyPluginPluginExport.h"

class dtkAbstractData;

class MYPLUGINPLUGIN_EXPORT MyPluginDefaultDataWriter : public axlAbstractDataWriter
{
    Q_OBJECT
    
public :
    MyPluginDefaultDataWriter(void);
    ~MyPluginDefaultDataWriter(void);
    
public:
    QString identifier(void) const;
    QString description(void) const;
    QStringList handled(void) const;
    
    static bool registered(void);
    
public:
    bool accept(dtkAbstractData *data);
    bool reject(dtkAbstractData *data);
    
    QDomElement write(QDomDocument *doc, dtkAbstractData *data);
    
};

dtkAbstractDataWriter *createMyPluginDefaultDataWriter(void);

#endif //MYPLUGINDEFAULTDATAWRITER_H

