// /////////////////////////////////////////////////////////////////
// Generated by axel-plugin wizard
// /////////////////////////////////////////////////////////////////

/* (C) MyCompany */


/* Put a short description of your plugin here */

/* MyCompany-contact@mycompany.com-http://www.mycompany.com */

#ifndef MYPLUGINPLUGINEXPORT_H
#define MYPLUGINPLUGINEXPORT_H

#ifdef WIN32
#ifdef MYPLUGINPLUGIN_EXPORT
#define MYPLUGINPLUGIN_EXPORT __declspec(dllexport)
#else
#define MYPLUGINPLUGIN_EXPORT
#endif
#else
#define MYPLUGINPLUGIN_EXPORT
#endif

#endif

