// /////////////////////////////////////////////////////////////////
// Generated by axel-plugin wizard
// /////////////////////////////////////////////////////////////////

/* (C) MyCompany */


/* Put a short description of your plugin here */

/* MyCompany-contact@mycompany.com-http://www.mycompany.com */

#ifndef MYPLUGINDEFAULTDATAREADER_H
#define MYPLUGINDEFAULTDATAREADER_H

#include <axlCore/axlAbstractDataReader.h>

#include "MyPluginPluginExport.h"

class dtkAbstractData;

class MYPLUGINPLUGIN_EXPORT MyPluginDefaultDataReader : public axlAbstractDataReader
{
    Q_OBJECT
    
public :
    MyPluginDefaultDataReader(void);
    ~MyPluginDefaultDataReader(void);
    
public:
    QString identifier(void) const;
    QString description(void) const;
    QStringList handled(void) const;
    
    static bool registered(void);
    
public:
    bool accept(const QDomNode& node);
    bool reject(const QDomNode& node);
    
    dtkAbstractData *read(const QDomNode& node);
    
};

dtkAbstractDataReader *createMyPluginDefaultDataReader(void);

#endif //MYPLUGINDEFAULTDATAREADER_H

