// /////////////////////////////////////////////////////////////////
// Generated by axel-plugin wizard
// /////////////////////////////////////////////////////////////////

/* (C) MyCompany */


/* Put a short description of your plugin here */

/* MyCompany-contact@mycompany.com-http://www.mycompany.com */

#ifndef MYPLUGINDEFAULTDATA_H
#define MYPLUGINDEFAULTDATA_H

#include "MyPluginPluginExport.h"

#include "MyPluginPlugin.h"

#include <axlCore/axlAbstractData.h>

class MyPluginDefaultDataPrivate;

class MYPLUGINPLUGIN_EXPORT MyPluginDefaultData :  public axlAbstractData
{
    Q_OBJECT
    
public:
    /// Creates an uninitialized SplineSurface, which can only be assigned to
    /// or read(...) into.
    MyPluginDefaultData(void);
    
    /// Virtual destructor, enables safe inheritance.
    virtual ~MyPluginDefaultData(void);
    
    virtual QString description(void) const;
    virtual QString identifier(void) const;
    virtual QString objectType(void) const;
    
    static bool registered(void);
    
private:
    MyPluginDefaultDataPrivate *d;
};

dtkAbstractData *createMyPluginDefaultData(void);

#endif //MYPLUGINDEFAULTDATA_H

