// /////////////////////////////////////////////////////////////////
// Generated by axel-plugin wizard
// /////////////////////////////////////////////////////////////////

/* (C) MyCompany */


/* Put a short description of your plugin here */

/* MyCompany-contact@mycompany.com-http://www.mycompany.com */

#ifndef MYPLUGINDEFAULTDATACREATORPROCESSDIALOG_H
#define MYPLUGINDEFAULTDATACREATORPROCESSDIALOG_H

# include <axlCore/axlAbstractData.h>
# include <axlGui/axlInspectorToolFactory.h>
#include "MyPluginPluginExport.h"

class MyPluginDefaultDataCreatorProcessDialogPrivate;

class MYPLUGINPLUGIN_EXPORT MyPluginDefaultDataCreatorProcessDialog : public axlInspectorToolInterface {
    Q_OBJECT
    
public:
    MyPluginDefaultDataCreatorProcessDialog(QWidget* parent = 0);
    virtual ~MyPluginDefaultDataCreatorProcessDialog();
    
    static bool registered(void);
    
signals:
    void dataInserted(axlAbstractData* data);
    
public slots:
    void run(void);
    
private:
    MyPluginDefaultDataCreatorProcessDialogPrivate* d;
    
};

dtkAbstractProcess* createProcessCreatorMyPluginDefaultData(void);
axlInspectorToolInterface* createMyPluginDefaultDataCreatorProcessDialog(void);

#endif // MYPLUGINDEFAULTDATACREATORPROCESSDIALOG_H

